quadrotor: 
  mass: 1.0 #kg
  inertia: [0.01, 0.01, 0.02] #kg*m^2 used for Torque Control
  g: 9.81 #m/s^2 
  thrustmod: "estimate" #thrustmod: "estimate" or "thrustmap"
  thrustmap: [0.0001, 6.4, 0] #thrustmap for all thrust=> thrust = thrustmap[0]*t^2 + thrustmap[1]*t + thrustmap[2] unit: N
  init_hover_thrust: 0.35 #unit, initial hover thrust for iterative thrust estimation
  max_thrust: 1.0 #unit
  min_thrust: 0.0 #unit
  max_bodyrate: 5 #rad/s for bodyrate control

controller: #geometry controller
  freq: 200
  # position loop: a_des = Kp_pos*(p_des - p) + Kd_pos*(v_des - v) + Ki_pos*(I_v + v_des - v)
  Kp_pos: 10 #position error gain
  Kd_pos: 4 #velocity error gain
  Ki_pos: 0 #integral error gain
  max_pos_error: 3.0 #max position error
  max_vel_error: 1.5 #max velocity error
  max_vel_int: 1.0 #max integral velocity, integration saturation

  bodyrate_control: false #bodyrate control flag, if true, bodyrate control is enabled else use quaternion(Px4 handle this)
  #bodyrate loop
  Kw: 5.0 #angular velocity error gain
  max_bodyrate_error: 5.0 #max bodyrate error

state_machine:
  freq: 200
  L2:
    takeoff_height: 1.0 #m
    idle_disarm_time: 10.0 #s
    cmd_ctrl_min_hz: 50 #Hz
    takeoff_landing_speed: 0.3 #m/s

guard: 
  freq: 200
  land_timeout: 5000 #ms after this time, disarm

  timeout_action: "land" #timeout_action: "land" or "disarm"
  mavros_timeout: 500 #ms
  odom_timeout: 30 #ms
  ui_timeout: 1000 #ms
  lowvolt_action: "land" #lowvolt_action: "land" or "disarm"
  low_battery_voltage: 19.0 #V